# -*- coding: utf-8 -*-
# git_verinfo.py - GSAS-II version info from git
# Do not edit, generated by 'GSASII/install/git_filters.py --record-version' command
# Created 2024-03-15 20:59:03.599761-05:00

git_version = 'cc3765c60b9d7b4cbfd93df3d58b2dcc68756f01'
git_tags = ['']
git_prevtaggedversion = '1c9ec36250ff954f3c32e757d6226949675e02ea'
git_prevtags = ['5760']
